apiVersion: v1
kind: Service
metadata:
  name: pos-api-service
  namespace: pos
  labels:
    app: pos-api
spec:
  type: LoadBalancer
  ports:
  - port: 35555
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: pos-api
  sessionAffinity: ClientIP
